from functions import *
import pprint

print "---------------------------------"
print "key-value PAIRS FOR ALL TAGS"
print "---------------------------------"
keys = ['maxspeed', 'currency:others', 'IRrouterank', 'seamark:construction', 'is_in', 'seamark:type',
        'created_by', 'to', 'crossing:barrier', 'fax', 'name:ur', 'icao', 'name:uk', 'motor_vehicle',
        'addr:street', 'source:name', 'AND_a_nosr_p', 'level', 'ref', 'nursery', 'protected_area',
        'subway', 'is_in:continent', 'source:tracer', 'sidewalk', 'bicycle', 'name:id', 'fuel:lpg',
        'ref:new', 'crop', 'name:is', 'area:highway', 'name:it', 'phone_2', 'phone_3', 'phone_1', 'cargo',
        'seamark:reflectivity', 'section', 'access', 'capital', 'fuel:e85', 'building:units', 'name:br',
        'water', 'name:bn', 'name:bh', 'name:be', 'name:bg', 'fuel:e10', 'name:yo', 'military', 'name:pt',
        'via', 'layer', 'tower:type', 'name:pa', 'name:pl', 'fee', 'from', 'public_transport:version',
        'gns:dsg', 'type', 'start_date', 'seamark:buoy_cardinal:category', 'entrance', 'name:ro',
        'end_date', 'motorroad', 'phone', 'train', 'currency:INR', 'uic_ref', 'fuel:GTL_diesel', 'tunnel',
        'name:ms', 'name:mr', 'lock', 'ISO3166-2', 'name:mg', 'name:ml', 'species', 'name:mk', 'name:fa',
        'name:fi', 'name:fr', 'product', 'iata', 'Tank', 'description', 'district',
        'seamark:buoy_cardinal:colour_pattern', 'fuel:1_50', 'wheelchair', 'outdoor_seating', 'addr:place',
        'fuel:cng', 'takeaway', 'restriction', 'office', 'building:part', 'name:th', 'postal_code',
        'motorcycle', 'int_ref', 'source:position', 'name:ta', 'name:tg', 'name:te', 'mini_roundabout',
        'kindergarten', 'fuel:1_25', 'after_school', 'covered', 'junction', 'seamark:buoy_cardinal:colour',
        'cutting', 'foot', 'tourism', 'smoothness', 'ref:old', 'payment:bitcoin', 'fixme', 'addr:city',
        'AND_a_c', 'tram', 'addr:state', 'AND_a_w', 'seamark:conspicuity', 'embankment', 'crossing',
        'name_1', 'name:as', 'name:ar', 'operator', 'frequency', 'loc_name', 'todo', 'building:fireproof',
        'name:af', 'network', 'brand:wikidata', 'name:zh', 'highway', 'name:sk', 'barrier',
        'seamark:information', 'electrified', 'name:sa', 'name:sv', 'name:sr', 'noexit', 'segregated',
        'route', 'atm', 'place', 'int_name', 'horse', 'service', 'addr:housename', 'station', 'name:hi',
        'name:he', 'park', 'is_in:state', 'seamark:buoy_cardinal:shape', 'natural', 'name:hu', 'name:hr',
        'Road', 'population', 'AND:importance_level', 'aeroway', 'seamark:mooring:category', 'landuse',
        'bridge', 'addr:suburb', 'generator:method', 'wikidata', 'foot_1', 'seamark:mooring:colour',
        'fuel:electricity', 'addr:district', 'building:levels', 'note', 'mooring', 'fuel:HGV_diesel',
        'building:colour', 'url', 'is_in:iso_3166_2', 'shop', 'golf', 'name:ka', 'name:ko', 'name:kn',
        'social_facility', 'name:ku', 'gauge', 'trail_visibility', 'is_in:city', 'name:tr', 'name:lv',
        'name:lt', 'name:cs', 'service_times', 'leisure', 'name:la', 'name:eo', 'name:en', 'addr:postcode',
        'motorboat', 'internet_access:fee', 'public_transport', 'name:eu', 'name:et', 'ruins', 'name:es',
        'is_capital', 'name:tl', 'wetland', 'parking', 'name:ru', 'sport', 'capacity', 'fuel:diesel',
        'wikipedia', 'seamark:buoy_lateral:category', 'boundary', 'email', 'addr:housenumber',
        'contact:email', 'denomination', 'building:use', 'substation', 'land_area', 'orphanage',
        'place:cca', 'tracks', 'leisure_1', 'leisure_2', 'railway', 'seamark:name', 'alt_name:pl',
        'seamark:buoy_lateral:system', 'name:oc', 'community', 'height', 'name:or', 'bench', 'boat',
        'bicycle_parking', 'website', 'lanes', 'building_1', 'craft', 'smoking', 'abandoned',
        'alt_name:eo', 'fuel:biogas', 'country', 'railway:traffic_mode', 'City', 'amenity', 'canoe',
        'toilets:disposal', 'surface', 'social_facility:for', 'name:vi', 'waterway', 'cuisine',
        'emergency', 'fuel:octane_98', 'GNS:id', 'fuel:octane_91', 'fuel:octane_95', 'drink', 'fence_type',
        'name:abbr', 'intermittent', 'colour', 'oneway', 'addr:country', 'name:cy', 'PARK',
        'drive_through', 'voltage', 'name:ca', 'lit', 'name:da', 'ele', 'source', 'usage', 'name:dv',
        'short_name', 'fuel:bio_diesel', 'gns:uni', 'seamark:buoy_lateral:shape', 'historic', 'name',
        'vending', 'designation', 'seamark:buoy_lateral:colour', 'internet_access', 'alt_name',
        'platforms', 'local_ref', 'man_made', 'religion', 'fuel:octane_100', 'name:de', 'artwork_type',
        'taluk', 'name:ja', 'power', 'incline', 'footway', 'supervised', 'aquaculture',
        'plant:output:electricity', 'IR:zone', 'generator:source', 'area', 'unisex', 'opening_hours',
        'museum', 'contact:phone', 'width', 'admin_level', 'bus', 'brand', 'ford', 'delivery',
        'construction', 'old_name', 'name:qu', 'passenger_lines', 'route_refs', 'route_master',
        'dispensing', 'seamark:status', 'maxheight', 'ship', 'cables', 'is_in:country', 'cycleway',
        'name:nl', 'name:nn', 'name:no', 'shelter', 'is_in:country_code', 'name:ne', 'min_height',
        'seamark:topmark:shape', 'AND_a_nosr_r', 'building', 'wifi', 'traffic_signals',
        'abandoned:aeroway', 'name:gu']

#keys = ["addr:city"]
x = get_key_modifiedvalue('tag', keys)
pprint.pprint(x)
